### ISSUE TITLE
Restart work on website + new render

### ISSUE THREAD

**Issue by Songtech-0912** [Shrinks99/NatronGitHub.github.io#5]
This is less of an issue, more of just a workaround for collaboration as discord doesn't really work in China.

I've made a new render that I hope can work for the CG compositing demo pic for the website:

![CG comp render](https://d2x313g9lpht1q.cloudfront.net/original/3X/a/0/a09ffc2fa0926938163a8959d961e9a66964d012.png)

I can send you the blender file and/or make you a proper exr with all the layers needed to properly comp with (let me know which you need) if you're onboard with using this render.

**Comment by Shrinks99** [comment]
Thanks for reminding me I need to stop this incredibly past-appropriate procrastination!

For CG compositing demo image it would be nice to have something with at least a few render layers that showcases what exactly those are.  Here we can do emission and a glow layer driven by that, anything else?  I don't think this scene would be the best representation of depth...

Got any others?  A landscape or render of some less abstract objects in a space might be a better fit??

**Comment by Songtech-0912** [comment]
Certainly, I can do another render of some scifi stuff where depth would be more apparent. Just as a FYI...disappointingly github is extremely slow and barely workable in China :( . Let's collab on the forum [here](https://discuss.pixls.us/t/natron-ui-re-design-proposal/18313/132)

**Comment by Shrinks99** [comment]
Closing this, looks like we have a V1 scoped, Will open a new issue for future features page development
